[mypy]
python_version = 3.10
warn_unused_configs = True
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = False
namespace_packages = False
explicit_package_bases = False
mypy_path = src
packages = bdf
plugins =

[mypy-bdf.repair]
ignore_errors = True

[mypy-bdf.metadata]
ignore_errors = True

[mypy-bdf.registry_ld]
ignore_errors = True

[mypy-bdf._explore]
ignore_errors = True

[mypy-bdf.cli]
ignore_errors = True
